### ISSUE TITLE
complain about fluxmap.pro

### ISSUE THREAD

**Issue by gzhao2014** [D3DEnergetic/nstx-fidasim#2]
@lstagner 
FYI
% Conflicting data structures: <LONG     (      142296)>,FLUXMAP.
% Execution halted at: FLUXMAP           180 /p/fida/FIDASIM/deps/efit/fluxmap.pro

**Comment by lstagner** [comment]
I haven't seen this error before. Could you give me more information so I could reproduce it.

**Comment by gzhao2014** [comment]
@lstagner 
1. Firstly, I copy the routines from /p/fida/FIDASIM
2. compile them as below 
3. the  work folder is '/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016;
4. When I try to check the fluxmap.pro. it seems that the problem relates to output:
   output = {fluxmap, shot:g.shot, time:g.time, $
         psi:psi, rho:rho, bcentr:bcentr}

```
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/vars_to_struct.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/nstx_chords.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/nstx_beams.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/lib/beam_grid.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/current_fractions.pro
.r /usr/pppl/itt/idl/idl82/lib/interpol.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/deps/efit/readg.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/nstx_prefida_GZ.pro
.r /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/nstx_inputs_GZ.pro
.r /p/nstxusr/nstx-users/ghao/CODE/FIDASIM/deps/efit/fluxmap.pro
.r /p/fida/FIDASIM/deps/efit/fluxmap.pro
x=nstx_inputs()
nstx_prefida,x
```

**Comment by gzhao2014** [comment]
**Finally, when I tried again, the issue in the first floor disappears. The code can run normally**

**Comment by lstagner** [comment]
I was about to say that I was unable to reproduce the error. I guess somewhere along the line you polluted your namespace. I did fix a name collision so you should update either by using git or just copying from my area.
