### ISSUE TITLE
NSTX check

### ISSUE THREAD

**Issue by gzhao2014** [D3DEnergetic/nstx-fidasim#5]
@lstagner  I'll to test 141648E01, since this shot is similar with that I am studying.

Before next step. I am wondering,  FIDASIM results may depend the how to generate gfile. As you know, there are different options, such as EFIT1,2 & LRDFIT1,...,6.

For the same shot, if we use different version of g-file, Do the final results have a big difference?

**Comment by lstagner** [comment]
It can. It would affect the transformation from pitch to velocity and stark splitting calculation.

**Comment by gzhao2014** [comment]
For reference, I re-run NSTX141648(just FBM method)(peak near 109cm)
![141648](https://cloud.githubusercontent.com/assets/15125494/15609623/170e4d60-23ef-11e6-9223-5f4a094350a3.PNG)

Bill's figure in 2016NF manuscript(peak near 113cm)
![bill](https://cloud.githubusercontent.com/assets/15125494/15609644/3b262a88-23ef-11e6-945c-2940d19bfc40.PNG)

**Comment by lstagner** [comment]
I would suggest rolling back to FIDASIM commit 055d31f7d64122dc1dcee3c198a13dfd3812c666 which was the last commit before I made the gyrocenter fix. I would be good to know what it predicts.

**Comment by lstagner** [comment]
In the above figure, did you apply any normalization?

**Comment by gzhao2014** [comment]
Yes. normalized the experiment to the theory data. Here, I just run FBM case. Pls neglect red curve.

**Comment by lstagner** [comment]
Normalized by integration or by largest value? What is its normalization constant? Could you plot the theory and the un-normalized experimental data?

**Comment by gzhao2014** [comment]
By largest value。 To make the experiment peak value equals to that of theory. Because, I don't not the calibration data between the CCD count and photons. I will plot them, respectively. 
![23](https://cloud.githubusercontent.com/assets/15125494/15624716/bb1dc598-245d-11e6-948e-e64b87dc4d3e.png)

![4](https://cloud.githubusercontent.com/assets/15125494/15624717/bd96ec28-245d-11e6-861e-6e20220fb939.png)

**Comment by gzhao2014** [comment]
It seems that the following file being for NSTX-U. While we check the shot on 2010. I am wondering Does it matter?
/p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/geometry/nstx_beams.h5

In addition, I plot the neutrals that we used during FIDA calculation. It seems to be reasonable.
![8888](https://cloud.githubusercontent.com/assets/15125494/15724055/672bb68e-2813-11e6-94ae-b3fa6f26f8e3.PNG)

**Comment by lstagner** [comment]
I created that file to hold the neutral beam geometry. I chose to read the geometry from a file instead of hard coding it into a routine so if we were to ever switch away from IDL the transition would be easier. 

As far as I know the neutral beam geometry is correct but I would check with Deyong to be certain.

**Comment by gzhao2014** [comment]
Ok. In addition,I plot the weight function at R=117cm, lambda=652.09nm. I'm not sure if it is reasonable? could you pls have a check on the weight function for our NSTX case?
![777](https://cloud.githubusercontent.com/assets/15125494/15728404/2b0fac66-282a-11e6-8d27-4fc446882107.PNG)

**Comment by lstagner** [comment]
@gzhao2014 Deyong and I will be taking a look at this in an hour or so. Could you create a directory with all your inputs for FIDASIM as well as the experimental data so we can track down the problem.

**Comment by gzhao2014** [comment]
The inputs files are stored in 
/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_BENCHMARK/inputs_files

Experiment data can be found following the note file 
/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_BENCHMARK/note

**Comment by lstagner** [comment]
Closing this for now.
