### ISSUE TITLE
submit job issue

### ISSUE THREAD

**Issue by gzhao2014** [D3DEnergetic/nstx-fidasim#6]
Because the update of PPPL cluster in Jan. 2017, there is an issue during my FIDASIM job submittion

1./p/fida/FIDASIM/fidasim /p/nstxusr/user/ghao/FIDASIM_RESULT/204092H02/RESULTS/970_inputs.dat
/p/fida/FIDASIM/fidasim: error while loading shared libraries: libirng.so: cannot open shared object file: No such file or directory

2. to use submit_fidasim script, also have another issue
/p/nstxusr/user/ghao/FIDASIM_RESULT/204092H02/RESULTS/360_inputs.dat
sbatch: error: Batch job submission failed: No partition specified or system default partition

which module should be loaded? or need to change the path setting? Thanks

**Comment by lstagner** [comment]
Here are my loaded modules
```
[lstagner@sunfire02]% module list
Currently Loaded Modulefiles:
  1) slurm/15.08.8         7) idl/8.4              13) nstx/setup
  2) ppplcluster/1.2       8) nstx/idldirs_newdir  14) acml/4.2.0-64bit
  3) intel/2013.1.3        9) nstx/treedefs        15) ntcc/PS_64
  4) git/1.8.0.2          10) nstx/epics           16) anaconda2/4.2.0
  5) pathscale/3.2        11) nstx/dcps            17) julia/0.5.1
  6) java/1.6.0_02        12) nstx/mdsplus
[lstagner@sunfire02]% 
```
The problem is probably caused by having the wrong Intel compiler

**Comment by gzhao2014** [comment]
Yes. It works now. Many thanks.
